id: A2BC46C4F
title: 'The Yearning Song that Swiftly Inspires Compassion: A Prayer to the Vajradhara
  Gurus, the Gentle Protectors'
type: translation
pechas:
- I075434A3
- IE1DD929A
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:59:33.868720
  last_modified_at: 2023-01-04 11:59:33.868729
  collections:
  - Gyurme Tsewang Gyatso Series
  - Works of Tibetan Masters
alignment_to_base:
  I075434A3/A053: 8A08
  IE1DD929A/8969: 8A08
